### ISSUE TITLE
Sled Racing Seating Bug

### ISSUE THREAD

**Issue by tootyta** [titshacking/RBSE#10]
This is just a small bug, so basically let's say I join a sled racing game and someone enters the room, they won't see that I'm in a tube http://prntscr.com/fmi3hx . I'll just be on the ground. http://prntscr.com/fmi3hx

**Comment by fantasyhacking** [comment]
The issue should be fixed now but I'm keeping this open because there is another bug with the seating, where when two users join a three sled game, and one of them decides to leave and join again, it joins on the same seat as the one already in the game and hasn't left and then it changes both the usernames to the one that is going to take a seat. Short and sweet, there is a seating issue on which I'm working on.

**Comment by fantasyhacking** [comment]
The issues with sled racing should be fixed now!
